# -*- coding: utf-8 -*-
"""Consommation Electrique avec Pandas .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ZUip9ggOGCNG34BjMDVRnlgur9zlI99
"""

# ------------------------------------------
# 1. Importation des bibliothèques
# ------------------------------------------
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (14, 5)

# ------------------------------------------
# 2. Chargement du Dataset
# Mettre votre fichier dans Google Colab puis adapter le chemin
# ------------------------------------------
file_path = "/content/household_power_consumption.txt"  # Modifier si nécessaire

df = pd.read_csv(
    file_path,
    sep=';',
    low_memory=False,
    na_values='?',
    parse_dates={'Datetime': ['Date', 'Time']},
    infer_datetime_format=True
)

# ------------------------------------------
# 3. Nettoyage des données
# ------------------------------------------
df = df.dropna()  # Suppression des valeurs manquantes
df.set_index('Datetime', inplace=True)

# Conversion des colonnes en float
for col in df.columns:
    df[col] = df[col].astype(float)

print("Aperçu des données :")
display(df.head())

# ------------------------------------------
# 4.Resampling → données par jour
# ------------------------------------------
df_daily = df.resample('D').mean()

print("Aperçu données journalières :")
display(df_daily.head())

# ------------------------------------------
# 5. Visualisation Consommation globale
# ------------------------------------------
plt.figure()
plt.title("Évolution de la puissance active (kW) sur la période")
plt.plot(df_daily['Global_active_power'])
plt.ylabel("Puissance active moyenne (kW)")
plt.xlabel("Années")
plt.show()

# ------------------------------------------
# 6. Analyse des sous-compteurs
# ------------------------------------------
plt.figure()
plt.title("Évolution des Sub Metering (Wh) par jour")
plt.plot(df_daily[['Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3']])
plt.legend(['Cuisine', 'Buanderie', 'Chauffe-eau / Clim'])
plt.show()

# ------------------------------------------
# 7. Analyse des corrélations
# ------------------------------------------
corr = df_daily.corr()

plt.figure(figsize=(10, 6))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Corrélation entre les variables")
plt.show()

print("Analyse terminée ! ✔")

# ------------------------------------------
# 7. Regression lineaire
# ------------------------------------------
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Préparation des données pour la régression linéaire
X = df_daily.drop('Global_active_power', axis=1)  # Variables explicatives
y = df_daily['Global_active_power']              # Variable cible

# Supprimer les lignes avec des NaN qui pourraient avoir été introduits par le resample si des jours entiers sont manquants
X = X.dropna()
y = y[X.index] # Align y with the cleaned X index

# Séparation des données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Taille de l'ensemble d'entraînement (X_train): {X_train.shape}")
print(f"Taille de l'ensemble de test (X_test): {X_test.shape}")

# Initialisation et entraînement du modèle de régression linéaire
model = LinearRegression()
model.fit(X_train, y_train)

# Prédictions sur l'ensemble de test
y_pred = model.predict(X_test)

# Évaluation du modèle
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"\nPerformance du modèle de régression linéaire :")
print(f"Erreur Quadratique Moyenne (MSE) : {mse:.2f}")
print(f"Coefficient de Détermination (R²) : {r2:.2f}")

plt.figure(figsize=(12, 6))
plt.scatter(y_test, y_pred, alpha=0.7)
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--', lw=2)
# Ligne de référence y=x
plt.xlabel("Valeurs Actuelles de Global_active_power (kW)")
plt.ylabel("Valeurs Prédites de Global_active_power (kW)")
plt.title("Régression Linéaire : Valeurs Actuelles vs. Prédites")
plt.grid(True)
plt.show()

# Afficher les coefficients du modèle
print("Coefficients du modèle :")
for feature, coef in zip(X.columns, model.coef_):
    print(f"{feature}: {coef:.4f}")
print(f"Intercept: {model.intercept_:.4f}")